services:
  pokus_pipeline:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: pokus_pipeline
    volumes:
      - ../projects/pokus-short:/studio/project
      - ./pipeline_scripts:/studio/pipeline_scripts
      - ./config:/studio/config
    working_dir: /studio
    tty: true
