project:
  - preproduction:
      - references
      - storyboards
      - designs:
          - characters:
              - char_poku:
                  - exports
  - production:
      - assets:
          - characters
          - props
          - environments
      - shots:
          - sh001
          - sh002
          - sh003
          - sh004
          - sh005
          - sh006
          - sh007
          - sh008
          - sh009
  - renders:
      - previews
  - database
